#!/usr/bin/env bash

if [[ -s "/home/ec2-user/.rvm/environments/ruby-2.0.0-p247" ]]
then
  source "/home/ec2-user/.rvm/environments/ruby-2.0.0-p247"
  exec erb "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/ec2-user/.rvm/environments/ruby-2.0.0-p247'" >&2
  exit 1
fi
