#!/usr/bin/env bash

if [[ -s "/home/ec2-user/.rvm/environments/ruby-2.0.0-p247@global" ]]
then
  source "/home/ec2-user/.rvm/environments/ruby-2.0.0-p247@global"
  exec testrb "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/ec2-user/.rvm/environments/ruby-2.0.0-p247@global'" >&2
  exit 1
fi
